# SPDX-License-Identifier: Apache-2.0

SOLOMON_TEST_LOCAL_MODEL_URL ?= http://127.0.0.1:11434/api/generate
SOLOMON_TEST_LOCAL_MODEL_NAME ?= qwen2.5-coder:1.5b

.PHONY: demo-local
demo-local:
	SOLOMON_TEST_LOCAL_MODEL_URL="$(SOLOMON_TEST_LOCAL_MODEL_URL)" SOLOMON_TEST_LOCAL_MODEL_NAME="$(SOLOMON_TEST_LOCAL_MODEL_NAME)" scripts/demo_local_model.sh
