{{- if not .Values.storage.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "shibahama.fullname" . }}
  labels:
    {{- include "shibahama.labels" . | nindent 4 }}
  {{- if eq .Values.storage.destroyPolicy "preserve" }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
