"""Isolated vNext decision-support package namespace."""

from stonks_cli.vnext.account_import import import_moomoo_accounts
from stonks_cli.vnext.boundaries import PACKAGE_BOUNDARIES, PackageBoundary, VNextPackage, validate_package_boundaries
from stonks_cli.vnext.capabilities import Capability, CapabilityRegistry
from stonks_cli.vnext.container import ServiceContainer
from stonks_cli.vnext.crypto_liquidity import filter_crypto_universe_by_liquidity
from stonks_cli.vnext.crypto_market_cap import (
    CryptoMarketCapAsset,
    CryptoMarketCapBatch,
    CryptoMarketCapProvider,
    fetch_crypto_market_caps,
)
from stonks_cli.vnext.crypto_metadata import (
    CryptoAssetMetadata,
    CryptoAssetMetadataProvider,
    CryptoAssetPlatform,
    ingest_crypto_asset_metadata,
)
from stonks_cli.vnext.crypto_universe_changes import (
    CryptoUniverseChanges,
    CryptoUniverseRankChange,
    detect_crypto_universe_changes,
)
from stonks_cli.vnext.crypto_universe_history import (
    CRYPTO_UNIVERSE_HISTORY_VERSION,
    CryptoUniverseHistory,
    append_crypto_universe_history,
    load_crypto_universe_history,
    save_crypto_universe_history,
)
from stonks_cli.vnext.crypto_universe_snapshot import (
    CRYPTO_UNIVERSE_SNAPSHOT_VERSION,
    CryptoUniverseSnapshot,
    create_crypto_universe_snapshot,
    load_crypto_universe_snapshot,
    save_crypto_universe_snapshot,
)
from stonks_cli.vnext.crypto_venues import (
    CryptoResearchVenue,
    CryptoVenueAssetSupport,
    filter_crypto_universe_by_supported_venues,
)
from stonks_cli.vnext.daily_closing_prices import DailyClosingPriceIngestion, ingest_daily_closing_prices
from stonks_cli.vnext.database import SQLiteConnectionFactory
from stonks_cli.vnext.errors import (
    OpenDContextIncompatibleError,
    OpenDDataEntitlementMissingError,
    OpenDEndpointUnavailableError,
    OpenDError,
    OpenDQuotaExceededError,
    OpenDResponseMalformedError,
    VNextApplicationError,
    VNextConfigurationError,
    VNextExecutionDeniedError,
    VNextExternalDataError,
    VNextInvariantError,
)
from stonks_cli.vnext.events import (
    EVENT_SCHEMA_VERSION,
    EventSeverity,
    StructuredEvent,
    create_structured_event,
    deserialize_structured_event,
    serialize_structured_event,
)
from stonks_cli.vnext.exchange_time import ExchangeTimeZone, normalize_exchange_timestamp
from stonks_cli.vnext.filesystem import (
    PRIVATE_DIRECTORY_MODE,
    PRIVATE_FILE_MODE,
    enforce_private_file,
    ensure_private_directory,
)
from stonks_cli.vnext.fixtures import (
    FIXTURE_EVENT_IDS,
    FIXTURE_RUN_ID,
    FIXTURE_RUN_STARTED_AT,
    deterministic_fixture_event_jsonl,
    deterministic_fixture_events,
    deterministic_fixture_run,
)
from stonks_cli.vnext.foundation import (
    RUN_IDENTITY_VERSION,
    Clock,
    FrozenUTCClock,
    RunIdentity,
    SecretReference,
    SystemUTCClock,
    UTCDateTime,
    as_utc,
    create_run_identity,
    load_run_identity,
    resolve_environment_secret,
    save_run_identity,
)
from stonks_cli.vnext.health import HealthCheck, HealthReport, HealthResult, HealthStatus, run_health_checks
from stonks_cli.vnext.lifecycle import ApplicationLifecycle, LifecycleHook, LifecycleState
from stonks_cli.vnext.market_calendar import (
    NYSECashEquityCalendar2026,
    SGMarketSession,
    SGMarketSessionStatus,
    SGXCashEquityCalendar2026,
    USMarketSession,
    USMarketSessionStatus,
)
from stonks_cli.vnext.market_data_provenance import (
    MarketDataProvenance,
    ProvenancedCryptoMarketCapBatch,
    attach_market_data_provenance,
)
from stonks_cli.vnext.market_data_refresh import MoomooQuote, refresh_moomoo_market_data
from stonks_cli.vnext.market_status import MarketStatus, MarketStatusReport, MarketStatusService, MarketVenue
from stonks_cli.vnext.migrations import Migration, MigrationRegistry, MigrationRunner
from stonks_cli.vnext.moomoo import (
    LocalOpenDReadOnlyClient,
    LocalOpenDReadOnlyConnection,
    MoomooAccount,
    MoomooAccountBalance,
    MoomooCashFlow,
    MoomooCorporateAction,
    MoomooHistoricalCandle,
    MoomooHistoricalOrder,
    MoomooInstrument,
    MoomooMarketDataEntitlements,
    MoomooMarketDataSubscription,
    MoomooOpenDProcessContract,
    MoomooOpenOrder,
    MoomooOrderHistoryWindow,
    MoomooPosition,
    MoomooReadOnlyAccountClient,
    MoomooReadOnlyBalanceClient,
    MoomooReadOnlyCashFlowClient,
    MoomooReadOnlyHistoricalCandleClient,
    MoomooReadOnlyMarketDataEntitlementClient,
    MoomooReadOnlyOpenOrderClient,
    MoomooReadOnlyOrderHistoryClient,
    MoomooReadOnlyPositionClient,
    MoomooReadOnlySGQuoteClient,
    MoomooReadOnlyUSQuoteClient,
    MoomooSdkCompatibility,
    MoomooSdkStatus,
    MoomooSGQuote,
    MoomooTradeUnlockEvidence,
    MoomooTradeUnlockState,
    MoomooUSQuote,
    OpenDEndpointProbe,
    OpenDEndpointStatus,
    check_moomoo_sdk_compatibility,
    normalize_moomoo_corporate_actions,
    normalize_moomoo_instruments,
    probe_local_opend,
    read_moomoo_trade_unlock_state_without_secrets,
    require_moomoo_data_entitlement,
    resolve_moomoo_sgx_equity_symbol,
    resolve_moomoo_us_equity_symbol,
    select_moomoo_account,
)
from stonks_cli.vnext.opend_fixture import RecordedOpenDCall, RecordedOpenDFixtureAdapter
from stonks_cli.vnext.price_data import (
    CanonicalDailyClose,
    CanonicalPriceDataProvider,
    CanonicalPriceSeries,
    fetch_canonical_daily_closes,
)
from stonks_cli.vnext.rate_limit import ReadOnlyRateLimiter
from stonks_cli.vnext.retry import IdempotentReadRetryPolicy, retry_idempotent_read
from stonks_cli.vnext.runtime import RUNTIME_ROOT_ENV, RuntimeDirectories, RuntimeDirectory, runtime_directories
from stonks_cli.vnext.snapshot_cache import IdempotentSnapshotCache
from stonks_cli.vnext.stablecoins import (
    DEFAULT_STABLECOIN_PROVIDER_ASSET_IDS,
    StablecoinClassification,
    StablecoinClassifier,
    StablecoinStatus,
    classify_stablecoins,
)

__all__ = [
    "Clock",
    "ApplicationLifecycle",
    "Capability",
    "CapabilityRegistry",
    "CanonicalDailyClose",
    "CanonicalPriceDataProvider",
    "CanonicalPriceSeries",
    "CryptoMarketCapAsset",
    "CryptoMarketCapBatch",
    "CryptoMarketCapProvider",
    "CryptoAssetMetadata",
    "CryptoAssetMetadataProvider",
    "CryptoAssetPlatform",
    "CryptoResearchVenue",
    "CryptoUniverseSnapshot",
    "CryptoUniverseChanges",
    "CryptoUniverseHistory",
    "CryptoUniverseRankChange",
    "CryptoVenueAssetSupport",
    "CRYPTO_UNIVERSE_SNAPSHOT_VERSION",
    "CRYPTO_UNIVERSE_HISTORY_VERSION",
    "DEFAULT_STABLECOIN_PROVIDER_ASSET_IDS",
    "DailyClosingPriceIngestion",
    "EventSeverity",
    "ExchangeTimeZone",
    "EVENT_SCHEMA_VERSION",
    "FIXTURE_EVENT_IDS",
    "FIXTURE_RUN_ID",
    "FIXTURE_RUN_STARTED_AT",
    "FrozenUTCClock",
    "HealthCheck",
    "HealthReport",
    "HealthResult",
    "HealthStatus",
    "IdempotentSnapshotCache",
    "IdempotentReadRetryPolicy",
    "LifecycleHook",
    "LifecycleState",
    "LocalOpenDReadOnlyClient",
    "LocalOpenDReadOnlyConnection",
    "PRIVATE_DIRECTORY_MODE",
    "PRIVATE_FILE_MODE",
    "Migration",
    "MigrationRegistry",
    "MigrationRunner",
    "MarketStatus",
    "MarketStatusReport",
    "MarketStatusService",
    "MarketVenue",
    "MarketDataProvenance",
    "MoomooOpenDProcessContract",
    "NYSECashEquityCalendar2026",
    "MoomooOpenOrder",
    "MoomooAccount",
    "MoomooAccountBalance",
    "MoomooCashFlow",
    "MoomooCorporateAction",
    "MoomooHistoricalCandle",
    "MoomooHistoricalOrder",
    "MoomooInstrument",
    "MoomooMarketDataEntitlements",
    "MoomooMarketDataSubscription",
    "MoomooOrderHistoryWindow",
    "MoomooReadOnlyAccountClient",
    "MoomooReadOnlyBalanceClient",
    "MoomooReadOnlyCashFlowClient",
    "MoomooReadOnlyHistoricalCandleClient",
    "MoomooReadOnlyMarketDataEntitlementClient",
    "MoomooReadOnlyOrderHistoryClient",
    "MoomooReadOnlyPositionClient",
    "MoomooReadOnlyOpenOrderClient",
    "MoomooReadOnlySGQuoteClient",
    "MoomooReadOnlyUSQuoteClient",
    "MoomooSdkCompatibility",
    "MoomooSdkStatus",
    "MoomooTradeUnlockEvidence",
    "MoomooTradeUnlockState",
    "MoomooSGQuote",
    "MoomooUSQuote",
    "MoomooPosition",
    "MoomooQuote",
    "OpenDEndpointProbe",
    "OpenDEndpointStatus",
    "OpenDContextIncompatibleError",
    "OpenDDataEntitlementMissingError",
    "OpenDEndpointUnavailableError",
    "OpenDError",
    "OpenDQuotaExceededError",
    "OpenDResponseMalformedError",
    "ProvenancedCryptoMarketCapBatch",
    "RecordedOpenDCall",
    "RecordedOpenDFixtureAdapter",
    "PACKAGE_BOUNDARIES",
    "PackageBoundary",
    "RUN_IDENTITY_VERSION",
    "RUNTIME_ROOT_ENV",
    "RunIdentity",
    "ReadOnlyRateLimiter",
    "SGXCashEquityCalendar2026",
    "SGMarketSession",
    "SGMarketSessionStatus",
    "SecretReference",
    "ServiceContainer",
    "SQLiteConnectionFactory",
    "StablecoinClassification",
    "StablecoinClassifier",
    "StablecoinStatus",
    "RuntimeDirectories",
    "RuntimeDirectory",
    "SystemUTCClock",
    "StructuredEvent",
    "UTCDateTime",
    "USMarketSession",
    "USMarketSessionStatus",
    "VNextApplicationError",
    "VNextConfigurationError",
    "VNextExecutionDeniedError",
    "VNextExternalDataError",
    "VNextInvariantError",
    "VNextPackage",
    "as_utc",
    "attach_market_data_provenance",
    "append_crypto_universe_history",
    "create_run_identity",
    "import_moomoo_accounts",
    "ingest_daily_closing_prices",
    "ingest_crypto_asset_metadata",
    "create_crypto_universe_snapshot",
    "create_structured_event",
    "fetch_crypto_market_caps",
    "fetch_canonical_daily_closes",
    "filter_crypto_universe_by_liquidity",
    "filter_crypto_universe_by_supported_venues",
    "check_moomoo_sdk_compatibility",
    "classify_stablecoins",
    "normalize_moomoo_instruments",
    "normalize_moomoo_corporate_actions",
    "normalize_exchange_timestamp",
    "deterministic_fixture_event_jsonl",
    "deterministic_fixture_events",
    "deterministic_fixture_run",
    "detect_crypto_universe_changes",
    "deserialize_structured_event",
    "enforce_private_file",
    "ensure_private_directory",
    "load_run_identity",
    "load_crypto_universe_history",
    "load_crypto_universe_snapshot",
    "resolve_environment_secret",
    "read_moomoo_trade_unlock_state_without_secrets",
    "refresh_moomoo_market_data",
    "require_moomoo_data_entitlement",
    "resolve_moomoo_us_equity_symbol",
    "resolve_moomoo_sgx_equity_symbol",
    "save_run_identity",
    "save_crypto_universe_history",
    "save_crypto_universe_snapshot",
    "serialize_structured_event",
    "select_moomoo_account",
    "runtime_directories",
    "retry_idempotent_read",
    "probe_local_opend",
    "run_health_checks",
    "validate_package_boundaries",
]
