# SPDX-License-Identifier: MIT

[package]
name = "shibahama-python"
description = "Python bindings for Shibahama."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "_shibahama"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
pyo3 = "0.28.3"
serde_json = "1.0.150"
shibahama-core.workspace = true
time = { version = "0.3.47", features = ["serde"] }
uuid = "1.23.3"

[dev-dependencies]
tempfile = "3.27.0"
