from __future__ import annotations

from stonks_cli.research.attribution import (
    FundingEvent,
    WalletRanking,
    WalletTradeOutcome,
    load_attribution_fixture,
    rank_wallets,
    rank_wallets_from_fixture,
    render_wallet_ranking_markdown,
)
from stonks_cli.research.capture_analysis import analyze_capture_archive
from stonks_cli.research.guards import evaluate_execution_guards, live_arm_env, live_execution_armed
from stonks_cli.research.hyperliquid import HyperliquidCarryInput, HyperliquidOrderClient
from stonks_cli.research.ingestion import (
    HyperliquidWebsocketIngestor,
    IngestionHealth,
    IngestionMonitor,
    capture_hyperliquid_to_files,
    replay_capture_fixture,
)
from stonks_cli.research.journal import append_decision, decision_journal_path, read_decisions
from stonks_cli.research.ledger import (
    build_tearsheet,
    load_replay_fixture,
    render_decision_ledger,
    render_tearsheet,
    write_fixture_artifacts,
)
from stonks_cli.research.models import (
    AttributionMetrics,
    BasisSnapshot,
    CarryDecision,
    CarryOpportunity,
    CarryPosition,
    CarryQuote,
    DecisionRecord,
    ExecutionIntent,
    ExecutionMode,
    FundingSnapshot,
    NormalizedTrade,
    TradeSide,
    Venue,
)
from stonks_cli.research.paper_analysis import PaperAnalysisConfig, PaperAnalysisEngine, replay_paper_analysis_fixture
from stonks_cli.research.validation_gates import (
    CAPTURE_GATE,
    GateAssessment,
    ValidationEvidence,
    ValidationGateState,
    assess_gate,
    default_validation_dir,
    record_capture_health,
    record_capture_probe,
    render_gate_report,
)

__all__ = [
    "AttributionMetrics",
    "BasisSnapshot",
    "CAPTURE_GATE",
    "CarryDecision",
    "CarryOpportunity",
    "CarryPosition",
    "CarryQuote",
    "DecisionRecord",
    "ExecutionIntent",
    "ExecutionMode",
    "FundingEvent",
    "FundingSnapshot",
    "GateAssessment",
    "HyperliquidCarryInput",
    "HyperliquidOrderClient",
    "HyperliquidWebsocketIngestor",
    "IngestionHealth",
    "IngestionMonitor",
    "NormalizedTrade",
    "PaperAnalysisConfig",
    "PaperAnalysisEngine",
    "TradeSide",
    "ValidationEvidence",
    "ValidationGateState",
    "Venue",
    "WalletRanking",
    "WalletTradeOutcome",
    "analyze_capture_archive",
    "append_decision",
    "assess_gate",
    "build_tearsheet",
    "capture_hyperliquid_to_files",
    "decision_journal_path",
    "default_validation_dir",
    "evaluate_execution_guards",
    "live_arm_env",
    "live_execution_armed",
    "load_attribution_fixture",
    "load_replay_fixture",
    "rank_wallets",
    "rank_wallets_from_fixture",
    "read_decisions",
    "record_capture_health",
    "record_capture_probe",
    "render_decision_ledger",
    "render_gate_report",
    "render_tearsheet",
    "render_wallet_ranking_markdown",
    "replay_capture_fixture",
    "replay_paper_analysis_fixture",
    "write_fixture_artifacts",
]
