# SPDX-License-Identifier: MIT

[package]
name = "shibahama-node"
description = "Node.js bindings for Shibahama."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
name = "shibahama"
crate-type = ["cdylib"]
path = "src/lib.rs"

[lints.rust]
missing_docs = "allow"
unsafe_code = "allow"

[dependencies]
napi = "3.9.1"
napi-derive = "3.5.6"
shibahama-core.workspace = true
time = { version = "0.3.47", features = ["serde"] }
uuid = "1.23.3"

[build-dependencies]
napi-build = "2.3.2"
