/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Iterator over recall candidates. */
export declare class RecallStream {
  /** Returns the number of remaining candidates. */
  remaining(): number
  /** Returns the next candidate, or null when exhausted. */
  next(): RecallCandidate | null
}

/** In-process Shibahama engine using the built-in HNSW vector index. */
export declare class Shibahama {
  /**
   * Opens a Shibahama store.
   *
   * # Errors
   *
   * Returns an error when the durable store cannot be opened.
   */
  constructor(path: string, dimensions: number, capacity?: number | undefined | null)
  /** Returns true when the native engine lock is healthy. */
  isOpen(): boolean
  /**
   * Writes a memory, optionally indexing an embedding vector.
   *
   * # Errors
   *
   * Returns an error when input validation, persistence, or vector indexing fails.
   */
  write(content: string, options?: WriteOptions | undefined | null): MemoryItem
  /**
   * Soft-invalidates a memory at a valid-time end.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or persistence fails.
   */
  invalidate(memoryId: string, validToUnix: number): boolean
  /**
   * Recalls current fact memories for a query embedding.
   *
   * # Errors
   *
   * Returns an error when vector search, storage reads, or access recording fail.
   */
  recall(queryVector: Array<number>, topK: number, options?: RecallOptions | undefined | null): Array<RecallCandidate>
  /**
   * Recalls usable candidates and reports unavailable optional stages.
   *
   * # Errors
   *
   * Returns an error when vector search or initial candidate materialization cannot complete.
   */
  recallWithDegradation(queryVector: Array<number>, topK: number, options?: RecallOptions | undefined | null): DegradedRecallResult
  /**
   * Streams current fact memories for a query embedding.
   *
   * # Errors
   *
   * Returns an error when vector search, storage reads, or access recording fail.
   */
  streamRecall(queryVector: Array<number>, topK: number, options?: RecallOptions | undefined | null): RecallStream
  /**
   * Replays recalled memories as they were believed at a historical instant.
   *
   * # Errors
   *
   * Returns an error when vector search or storage reads fail.
   */
  timeline(queryVector: Array<number>, topK: number, asOfUnix: number, options?: RecallOptions | undefined | null): Array<RecallCandidate>
  /**
   * Streams historical recall results.
   *
   * # Errors
   *
   * Returns an error when vector search or storage reads fail.
   */
  streamTimeline(queryVector: Array<number>, topK: number, asOfUnix: number, options?: RecallOptions | undefined | null): RecallStream
  /**
   * Records a usage outcome for a memory.
   *
   * # Errors
   *
   * Returns an error when the memory id or outcome is invalid, or persistence fails.
   */
  reinforce(memoryId: string, outcome?: string | undefined | null): boolean
  /**
   * Explains why a memory currently has its state.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or state cannot be read.
   */
  why(memoryId: string, nowUnix?: number | undefined | null): WhyTrace | null
  /**
   * Returns all current materialized memory rows.
   *
   * # Errors
   *
   * Returns an error when current item state cannot be read.
   */
  memoryItems(): Array<MemoryItem>
  /**
   * Returns durable event-log records as JSON.
   *
   * # Errors
   *
   * Returns an error when event records cannot be read or serialized.
   */
  eventRecordsJson(): string
  /**
   * Returns one memory's why trace and related events as JSON.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or storage cannot be read.
   */
  auditJson(memoryId: string, nowUnix?: number | undefined | null): string
  /**
   * Runs the offline consolidation pass and returns its report as JSON.
   *
   * # Errors
   *
   * Returns an error when consolidation cannot be planned or applied.
   */
  consolidateJson(nowUnix?: number | undefined | null): string
  /**
   * Challenges a memory and returns the mutation report as JSON.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or persistence fails.
   */
  challengeJson(memoryId: string, reason: string, actor?: string | undefined | null, timestampUnix?: number | undefined | null): string
  /**
   * Affirms a memory and returns the mutation report as JSON.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or persistence fails.
   */
  affirmJson(memoryId: string, reason?: string | undefined | null, actor?: string | undefined | null, timestampUnix?: number | undefined | null): string
  /**
   * Pins a memory and returns the mutation report as JSON.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or persistence fails.
   */
  pinJson(memoryId: string, reason?: string | undefined | null, actor?: string | undefined | null, timestampUnix?: number | undefined | null): string
  /**
   * Unpins a memory and returns the mutation report as JSON.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or persistence fails.
   */
  unpinJson(memoryId: string, reason?: string | undefined | null, actor?: string | undefined | null, timestampUnix?: number | undefined | null): string
  /**
   * Corrects a memory and returns the mutation report as JSON.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or persistence fails.
   */
  correctJson(memoryId: string, proposedContent: string, reason?: string | undefined | null, actor?: string | undefined | null, timestampUnix?: number | undefined | null): string
}

/** Returns the versioned capability document as JSON. */
export declare function capabilitiesJson(): string

export interface DegradedRecallResult {
  candidates: Array<RecallCandidate>
  unavailableStages: Array<string>
}

export interface MemoryItem {
  id: string
  content: string
  kind: string
  provenance: Provenance
  scope: MemoryScope
  tier: string
  credence: string
  significance: number
  credenceFloor: string
  validFromUnix: number
  validToUnix?: number
  ingestedAtUnix: number
}

export interface MemoryScope {
  repository: string
  team?: string
  visibility: string
}

export interface Provenance {
  sourceKind: string
  sourceRef?: string
  ingestedBy: string
}

export interface RecallCandidate {
  id: string
  item: MemoryItem
  kind: string
  provenance: Provenance
  tier: string
  currency: string
  loadBearingPossiblyStale: boolean
  coldTierRetrieval: boolean
  vectorDistance: number
  similarityScore: number
  significanceScore: number
  recencyScore: number
  graphScore: number
  source: string
  rankScore: number
  readSafetyFindings: Array<string>
}

export interface RecallOptions {
  nowUnix?: number
  rawQueryContext?: string
  includeCold?: boolean
  includeInstructions?: boolean
  maxContextTokens?: number
  similarityWeight?: number
  significanceWeight?: number
  recencyWeight?: number
  graphWeight?: number
}

export interface SignificanceBreakdown {
  baseScore: number
  decayMultiplier: number
  decayedBase: number
  reinforcement: number
  outcomeBonus: number
  contradictionPenalty: number
  graphCentrality: number
  finalScore: number
}

/** Returns the Shibahama core crate version. */
export declare function version(): string

export interface WhyTrace {
  item: MemoryItem
  significance: SignificanceBreakdown
  provenance: Provenance
  tierCurrent: string
  tierCredence: string
  tierCredenceFloor: string
  currencyState: string
  currencyAsOfUnix: number
  validFromUnix: number
  validToUnix?: number
  ingestedAtUnix: number
  auditTrail: Array<string>
}

export interface WriteOptions {
  vector?: Array<number>
  sourceKind?: string
  sourceRef?: string
  ingestedBy?: string
  validFromUnix?: number
  ingestedAtUnix?: number
  kind?: string
  indexName?: string
  model?: string
  modelVersion?: string
  scope?: MemoryScope
}

// Shibahama JavaScript shims
export interface CapabilityDocument {
  schemaVersion: number
  version: string
  memorySchemaVersion: number
  capabilities: Array<string>
}

export declare function capabilities(): CapabilityDocument

export interface ShibahamaError extends Error {
  code: string
  severity: "recoverable" | "fatal"
  retryable: boolean
  detail: string
}

export type EmbedFunction = (text: string) => Array<number> | Promise<Array<number>>

export interface LangChainMemoryOptions {
  embed: EmbedFunction
  memoryKey?: string
  inputKey?: string
  outputKey?: string
  topK?: number
}

export interface Shibahama {
  eventRecords(): Record<string, unknown>
  audit(memoryId: string, nowUnix?: number | undefined | null): Record<string, unknown>
  consolidate(nowUnix?: number | undefined | null): Record<string, unknown>
  challenge(
    memoryId: string,
    reason: string,
    actor?: string | undefined | null,
    timestampUnix?: number | undefined | null,
  ): Record<string, unknown>
  affirm(
    memoryId: string,
    reason?: string | undefined | null,
    actor?: string | undefined | null,
    timestampUnix?: number | undefined | null,
  ): Record<string, unknown>
  correct(
    memoryId: string,
    proposedContent: string,
    reason?: string | undefined | null,
    actor?: string | undefined | null,
    timestampUnix?: number | undefined | null,
  ): Record<string, unknown>
  pin(
    memoryId: string,
    reason?: string | undefined | null,
    actor?: string | undefined | null,
    timestampUnix?: number | undefined | null,
  ): Record<string, unknown>
  unpin(
    memoryId: string,
    reason?: string | undefined | null,
    actor?: string | undefined | null,
    timestampUnix?: number | undefined | null,
  ): Record<string, unknown>
}

export declare class LangChainMemory {
  constructor(engine: Shibahama, options: LangChainMemoryOptions)
  readonly engine: Shibahama
  readonly embed: EmbedFunction
  readonly memoryKey: string
  readonly inputKey: string
  readonly outputKey: string
  readonly topK: number
  readonly memoryKeys: Array<string>
  readonly memoryVariables: Array<string>
  loadMemoryVariables(inputs: Record<string, unknown>): Promise<Record<string, string>>
  saveContext(inputs: Record<string, unknown>, outputs: Record<string, unknown>): Promise<void>
  clear(): Promise<void>
}
