/* auto-generated by NAPI-RS */
/* eslint-disable */
/** In-process Shibahama engine using the built-in HNSW vector index. */
export declare class Shibahama {
  /**
   * Opens a Shibahama store.
   *
   * # Errors
   *
   * Returns an error when the durable store cannot be opened.
   */
  constructor(path: string, dimensions: number, capacity?: number | undefined | null)
  /** Returns true when the native engine lock is healthy. */
  isOpen(): boolean
}

/** Returns the Shibahama core crate version. */
export declare function version(): string
