/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Iterator over recall candidates. */
export declare class RecallStream {
  /** Returns the number of remaining candidates. */
  remaining(): number
  /** Returns the next candidate, or null when exhausted. */
  next(): RecallCandidate | null
}

/** In-process Shibahama engine using the built-in HNSW vector index. */
export declare class Shibahama {
  /**
   * Opens a Shibahama store.
   *
   * # Errors
   *
   * Returns an error when the durable store cannot be opened.
   */
  constructor(path: string, dimensions: number, capacity?: number | undefined | null)
  /** Returns true when the native engine lock is healthy. */
  isOpen(): boolean
  /**
   * Writes a memory, optionally indexing an embedding vector.
   *
   * # Errors
   *
   * Returns an error when input validation, persistence, or vector indexing fails.
   */
  write(content: string, options?: WriteOptions | undefined | null): MemoryItem
  /**
   * Recalls current fact memories for a query embedding.
   *
   * # Errors
   *
   * Returns an error when vector search, storage reads, or access recording fail.
   */
  recall(queryVector: Array<number>, topK: number, options?: RecallOptions | undefined | null): Array<RecallCandidate>
  /**
   * Streams current fact memories for a query embedding.
   *
   * # Errors
   *
   * Returns an error when vector search, storage reads, or access recording fail.
   */
  streamRecall(queryVector: Array<number>, topK: number, options?: RecallOptions | undefined | null): RecallStream
  /**
   * Replays recalled memories as they were believed at a historical instant.
   *
   * # Errors
   *
   * Returns an error when vector search or storage reads fail.
   */
  timeline(queryVector: Array<number>, topK: number, asOfUnix: number, options?: RecallOptions | undefined | null): Array<RecallCandidate>
  /**
   * Streams historical recall results.
   *
   * # Errors
   *
   * Returns an error when vector search or storage reads fail.
   */
  streamTimeline(queryVector: Array<number>, topK: number, asOfUnix: number, options?: RecallOptions | undefined | null): RecallStream
  /**
   * Records a usage outcome for a memory.
   *
   * # Errors
   *
   * Returns an error when the memory id or outcome is invalid, or persistence fails.
   */
  reinforce(memoryId: string, outcome?: string | undefined | null): boolean
  /**
   * Explains why a memory currently has its state.
   *
   * # Errors
   *
   * Returns an error when the memory id is invalid or state cannot be read.
   */
  why(memoryId: string, nowUnix?: number | undefined | null): WhyTrace | null
  /**
   * Returns all current materialized memory rows.
   *
   * # Errors
   *
   * Returns an error when current item state cannot be read.
   */
  memoryItems(): Array<MemoryItem>
}

export interface MemoryItem {
  id: string
  content: string
  kind: string
  provenance: Provenance
  tier: string
  credence: string
  significance: number
  credenceFloor: string
  validFromUnix: number
  validToUnix?: number
  ingestedAtUnix: number
}

export interface Provenance {
  sourceKind: string
  sourceRef?: string
  ingestedBy: string
}

export interface RecallCandidate {
  id: string
  item: MemoryItem
  kind: string
  provenance: Provenance
  tier: string
  currency: string
  loadBearingPossiblyStale: boolean
  coldTierRetrieval: boolean
  vectorDistance: number
  similarityScore: number
  significanceScore: number
  recencyScore: number
  graphScore: number
  source: string
  rankScore: number
  readSafetyFindings: Array<string>
}

export interface RecallOptions {
  nowUnix?: number
  rawQueryContext?: string
  includeCold?: boolean
  includeInstructions?: boolean
}

export interface SignificanceBreakdown {
  baseScore: number
  decayMultiplier: number
  decayedBase: number
  reinforcement: number
  outcomeBonus: number
  contradictionPenalty: number
  graphCentrality: number
  finalScore: number
}

/** Returns the Shibahama core crate version. */
export declare function version(): string

export interface WhyTrace {
  item: MemoryItem
  significance: SignificanceBreakdown
  provenance: Provenance
  tierCurrent: string
  tierCredence: string
  tierCredenceFloor: string
  currencyState: string
  currencyAsOfUnix: number
  validFromUnix: number
  validToUnix?: number
  ingestedAtUnix: number
  auditTrail: Array<string>
}

export interface WriteOptions {
  vector?: Array<number>
  sourceKind?: string
  sourceRef?: string
  ingestedBy?: string
  validFromUnix?: number
  ingestedAtUnix?: number
  kind?: string
  indexName?: string
  model?: string
  modelVersion?: string
}
