[book]
title = "Shisa Documentation"
authors = ["Shisa maintainers"]
language = "en"
src = "."

[build]
build-dir = "../zig-out/mdbook"
create-missing = false

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
no-section-label = true
additional-css = ["theme/pagefind-search.css"]
additional-js = ["theme/pagefind-search.js"]
